function [cc] = Cfuct(t,v,phi,x,rho,state)
% function c in lemma 5.1, x is alpha
phi=phi(:);
x=x(:);
rho=rho(:);%rho(1)=rho_{1,2},rho(2)=rho_{1,3},rho(3)=rho_{2,3}
cc=(v-t)*(-thetastar1(state)*phi(1)-thetastar2(state,rho)*phi(2)-thetastar3(state,rho)*phi(3)+(sigma1(state)^2*phi(1)^2)/(2*g1(state)^2)+(sigma2(state)^2*phi(2)^2)/(2*g2(state)^2)+(sigma3(state)^2*phi(3)^2)/(2*g3(state)^2)+(rho(1)*phi(1)*phi(2)*sigma1(state)*sigma2(state))/(g1(state)*g2(state))+(rho(2)*phi(1)*phi(3)*sigma1(state)*sigma3(state))/(g1(state)*g3(state))+(rho(3)*phi(3)*phi(2)*sigma3(state)*sigma2(state))/(g3(state)*g2(state)))...
    +(exp(-g1(state)*(v-t))-1)*(x(1)+phi(1)/g1(state))*(-thetastar1(state)+(sigma1(state)^2*phi(1))/(g1(state)^2)+(phi(2)*rho(1)*sigma1(state)*sigma2(state))/(g1(state)*g2(state))+(phi(3)*rho(2)*sigma1(state)*sigma3(state))/(g1(state)*g3(state)))...
    +(exp(-g2(state)*(v-t))-1)*(x(2)+phi(2)/g2(state))*(-thetastar2(state,rho)+(sigma2(state)^2*phi(2))/(g2(state)^2)+(phi(1)*rho(1)*sigma1(state)*sigma2(state))/(g1(state)*g2(state))+(phi(3)*rho(3)*sigma2(state)*sigma3(state))/(g2(state)*g3(state)))...
    +(exp(-g3(state)*(v-t))-1)*(x(3)+phi(3)/g3(state))*(-thetastar3(state,rho)+(sigma3(state)^2*phi(3))/(g3(state)^2)+(phi(1)*rho(2)*sigma1(state)*sigma3(state))/(g1(state)*g3(state))+(phi(2)*rho(3)*sigma2(state)*sigma3(state))/(g2(state)*g3(state)))...
    +(exp(-2*g1(state)*(v-t))-1)*(-(sigma1(state)^2)/(4*g1(state))*(x(1)+phi(1)/g1(state))^2)...
    +(exp(-2*g2(state)*(v-t))-1)*(-(sigma2(state)^2)/(4*g2(state))*(x(2)+phi(2)/g2(state))^2)...
    +(exp(-2*g3(state)*(v-t))-1)*(-(sigma3(state)^2)/(4*g3(state))*(x(3)+phi(3)/g3(state))^2)...
    +(exp(-(g1(state)+g2(state))*(v-t))-1)*(-(rho(1)*sigma1(state)*sigma2(state))/(g1(state)+g2(state))*(x(1)+phi(1)/g1(state))*(x(2)+phi(2)/g2(state)))...
    +(exp(-(g1(state)+g3(state))*(v-t))-1)*(-(rho(2)*sigma1(state)*sigma3(state))/(g1(state)+g3(state))*(x(1)+phi(1)/g1(state))*(x(3)+phi(3)/g3(state)))...
    +(exp(-(g2(state)+g3(state))*(v-t))-1)*(-(rho(3)*sigma3(state)*sigma2(state))/(g3(state)+g2(state))*(x(3)+phi(3)/g3(state))*(x(2)+phi(2)/g2(state)));
end