function [ccc] = CCfuct(t,v,phi,x,xx,rho,state)
% function q in lemma 5.3 x is alpha and xx is beta
phi=phi(:);
x=x(:);
xx=xx(:);
rho=rho(:);%rho(1)=rho_{1,2},rho(2)=rho_{1,3},rho(3)=rho_{2,3}
ccc=-(exp(-g1(state)*(v-t))-1)*xx(1)*(thetastar1(state)-(phi(1)*sigma1(state)^2)/(g1(state)^2)-(phi(2)*rho(1)*sigma1(state)*sigma2(state))/(g1(state)*g2(state))-(phi(3)*rho(2)*sigma1(state)*sigma3(state))/(g1(state)*g3(state)))...
    -(exp(-g2(state)*(v-t))-1)*xx(2)*(thetastar2(state,rho)-(phi(2)*sigma2(state)^2)/(g2(state)^2)-(phi(1)*rho(1)*sigma1(state)*sigma2(state))/(g1(state)*g2(state))-(phi(3)*rho(3)*sigma2(state)*sigma3(state))/(g2(state)*g3(state)))...
    -(exp(-g3(state)*(v-t))-1)*xx(3)*(thetastar3(state,rho)-(phi(3)*sigma3(state)^2)/(g3(state)^2)-(phi(1)*rho(2)*sigma1(state)*sigma3(state))/(g1(state)*g3(state))-(phi(2)*rho(3)*sigma2(state)*sigma3(state))/(g2(state)*g3(state)))...
    -(exp(-2*g1(state)*(v-t))-1)*(sigma1(state)^2)/(2*g1(state))*(x(1)+phi(1)/g1(state))*xx(1)...
    -(exp(-2*g2(state)*(v-t))-1)*(sigma2(state)^2)/(2*g2(state))*(x(2)+phi(2)/g2(state))*xx(2)...
    -(exp(-2*g3(state)*(v-t))-1)*(sigma3(state)^2)/(2*g3(state))*(x(3)+phi(3)/g3(state))*xx(3)...
    -(exp(-(g1(state)+g2(state))*(v-t))-1)*((rho(1)*sigma1(state)*sigma2(state))/(g1(state)+g2(state))*((x(2)+phi(2)/g2(state))*xx(1)+(x(1)+phi(1)/g1(state))*xx(2)))...
    -(exp(-(g1(state)+g3(state))*(v-t))-1)*((rho(2)*sigma1(state)*sigma3(state))/(g1(state)+g3(state))*((x(3)+phi(3)/g3(state))*xx(1)+(x(1)+phi(1)/g1(state))*xx(3)))...
    -(exp(-(g2(state)+g3(state))*(v-t))-1)*((rho(3)*sigma3(state)*sigma2(state))/(g3(state)+g2(state))*((x(3)+phi(3)/g3(state))*xx(2)+(x(2)+phi(2)/g2(state))*xx(3)));
end